import React, { useState } from "react";
import { motion, AnimatePresence } from "motion/react";
import YourtLogo from "./YourtLogo";
import { 
  Sparkles, 
  ArrowRight, 
  Check, 
  HelpCircle, 
  ChevronDown, 
  ChevronUp, 
  FileText, 
  Upload, 
  Wand2, 
  BarChart3, 
  Play, 
  Zap, 
  Target, 
  Layers, 
  Eye, 
  Gauge, 
  CheckCircle2, 
  X,
  Plus,
  Tv,
  ExternalLink,
  ShieldAlert,
  Clock,
  Flame,
  ArrowUpRight,
  Anchor,
  Hash,
  Calendar,
  Heading,
  Lightbulb,
  ScrollText,
  Image as ImageIcon
} from "lucide-react";

interface LandingPageViewProps {
  onGetStarted: (mode: "signin" | "signup") => void;
}

export default function LandingPageView({ onGetStarted }: LandingPageViewProps) {
  // FAQ accordion state
  const [openFaq, setOpenFaq] = useState<number | null>(0);

  // Terminal active tab state
  const [activeTab, setActiveTab] = useState<"track" | "analyze" | "optimize">("track");

  // Newsletter state
  const [email, setEmail] = useState("");
  const [newsletterSubscribed, setNewsletterSubscribed] = useState(false);

  const faqs = [
    {
      q: "How do AI credits work?",
      a: "Every premium subscription comes bundled with monthly Pro credits. Trend analysis and CTR prediction consume 50/30 credits, script generation consumes 50 credits, and title optimizations or hooks utilize 10 credits. Unused regular credits roll over for up to 3 calendar months so you never lose what you don't use."
    },
    {
      q: "What tools are included in the Creator Suite?",
      a: "Yourt AI provides a complete suite of creator tools including: an Idea Generator, Hook Generator, Script Generator, Title Optimizer, Hashtag Optimizer, Trend Analyzer & CTR Predictor, and an interactive Content Calendar to organize your production schedule."
    },
    {
      q: "How fast are the creative assets generated?",
      a: "Scroll-stopping hooks, viral hashtags, and click-worthy title options take less than 3 seconds. High-retention 60-second video scripts take around 8 seconds, while trend analyses and CTR estimations take about 5 seconds."
    },
    {
      q: "Can I monetize content created with Yourt AI?",
      a: "Yes, absolutely! All scripts, ideas, hooks, titles, and hashtags generated by Yourt AI are 100% royalty-free and yours to monetize across YouTube, TikTok, Instagram Reels, or private client projects."
    },
    {
      q: "How is my content saved or synchronized?",
      a: "Everything you generate can be instantly saved. Your workspace is fully backed by Firestore cloud storage, meaning all your favorited concepts, scripts, and content calendar schedules are accessible across all your devices."
    }
  ];

  const handleSubscribeNewsletter = (e: React.FormEvent) => {
    e.preventDefault();
    if (email.trim() && email.includes("@")) {
      setNewsletterSubscribed(true);
      setTimeout(() => {
        setNewsletterSubscribed(false);
        setEmail("");
      }, 5000);
    }
  };

  return (
    <div className="bg-[#fbf9f9] text-[#1b1c1c] font-sans overflow-x-hidden selection:bg-[#ff6b00]/15 selection:text-[#ff6b00] min-h-screen flex flex-col justify-between" id="yourt-landing-root">
      
      {/* 1. GLASSMORPHIC TOP NAVIGATION GLASS */}
      <header className="sticky top-0 z-50 bg-[#fbf9f9]/85 backdrop-blur-xl border-b border-[#efeded]/60 px-4 sm:px-8 py-4 flex items-center justify-between transition-all" id="landing-navbar">
        <div className="flex items-center gap-2 select-none">
          <YourtLogo size={36} />
          <div className="flex flex-col">
            <span className="font-display font-black text-base text-[#0D0D0D] tracking-tight leading-none">Yourt AI</span>
            <span className="text-[9px] uppercase tracking-wider text-gray-400 font-bold mt-0.5 leading-none">Creator Suite</span>
          </div>
        </div>

        {/* Desktop Nav Links */}
        <nav className="hidden md:flex items-center gap-7 text-[#1b1c1c] text-xs font-semibold select-none">
          <a href="#features" className="hover:text-[#ff6b00] transition-colors">Features</a>
          <a href="#steps" className="hover:text-[#ff6b00] transition-colors">How It Works</a>
          <a href="#pricing" className="hover:text-[#ff6b00] transition-colors">Pricing</a>
          <a href="#faq" className="hover:text-[#ff6b00] transition-colors">FAQ</a>
        </nav>

        {/* Auth CTA actions */}
        <div className="flex items-center gap-3">
          <button 
            onClick={() => onGetStarted("signin")}
            className="text-xs font-bold text-gray-700 hover:text-[#ff6b00] px-3.5 py-2 rounded-xl transition-all cursor-pointer font-sans"
            id="nav-btn-login"
          >
            Login
          </button>
          <button 
            onClick={() => onGetStarted("signup")}
            className="bg-[#0D0D0D] hover:bg-[#ff6b00] text-white text-xs font-bold px-4.5 py-2.5 rounded-xl transition-all cursor-pointer shadow-3xs"
            id="nav-btn-signup"
          >
            Get Started
          </button>
        </div>
      </header>

      {/* 2. MAJESTIC HERO SECTION WITH BADGES */}
      <section className="px-4 sm:px-6 lg:px-8 max-w-[1280px] mx-auto pt-16 pb-20 text-center space-y-8 select-none" id="features">
        
        {/* Sparkle Pill Badge representation */}
        <div className="inline-flex items-center gap-1.5 bg-[#ff6b00]/10 border border-[#ff6b00]/25 rounded-full px-4 py-1.5 text-[10px] font-bold text-[#ff6b00] tracking-widest uppercase font-display animate-fade-in shadow-2xs">
          <Sparkles className="w-3.5 h-3.5" />
          YOURT AI CREATOR SUITE 2.0
        </div>

        {/* Aggressive Large Headline holding orange box pill */}
        <h1 className="font-display font-black text-4xl sm:text-6xl md:text-7xl text-[#0D0D0D] tracking-tight leading-[1.08] max-w-4xl mx-auto">
          Create viral shorts<br />
          in <span className="inline-block relative bg-[#ff6b00] text-white px-5 sm:px-7 py-1 sm:py-2.5 rounded-3xl transform -rotate-1 skew-x-1 shadow-md">seconds</span><br />
          with AI
        </h1>

        {/* Description / Subtitle font pairing */}
        <p className="text-sm sm:text-base text-gray-500 max-w-2xl mx-auto leading-relaxed font-sans">
          Stop guessing what works. Yourt AI uses advanced data models to generate high-retention scripts, viral hooks, and click-magnet titles in seconds.
        </p>

        {/* Massive Primary CTA Action */}
        <div className="flex flex-col sm:flex-row items-center justify-center gap-4 pt-4 font-sans">
          <button
            onClick={() => onGetStarted("signup")}
            className="w-full sm:w-auto inline-flex items-center justify-center gap-2.5 bg-[#ff6b00] hover:bg-[#e05e00] hover:scale-101 text-white font-bold text-sm px-8 py-4.5 rounded-2xl transition-all shadow-md animate-pulse cursor-pointer"
            id="hero-primary-cta"
          >
            Start Creating Free
            <ArrowRight className="w-4.5 h-4.5" />
          </button>
          
          <button
            onClick={() => onGetStarted("signin")}
            className="w-full sm:w-auto inline-flex items-center justify-center bg-white hover:bg-gray-50 text-gray-700 border border-gray-250 font-bold text-sm px-6 py-4.5 rounded-2xl transition-all shadow-3xs cursor-pointer"
          >
            Sign In to Account
          </button>
        </div>

        {/* Micro guarantees tick checks */}
        <div className="flex flex-wrap items-center justify-center gap-x-6 gap-y-2 text-[11px] text-gray-400 font-semibold uppercase tracking-wider font-mono pt-2">
          <div className="flex items-center gap-1.5">
            <span className="text-red-500 font-bold">✕</span> No credit card required
          </div>
          <div className="flex items-center gap-1.5">
            <span className="text-emerald-500">✓</span> 20 free credits included
          </div>
          <div className="flex items-center gap-1.5">
            <span className="text-[#ff6b00]">✓</span> Cancel anytime
          </div>
        </div>

        {/* Creator avatar list mockup */}
        <div className="flex items-center justify-center gap-3 pt-6 border-t border-gray-100 max-w-md mx-auto">
          <div className="flex -space-x-2.5">
            <img className="w-8 h-8 rounded-full border-2 border-white object-cover" src="https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&q=80&w=120" alt="creator" referrerPolicy="no-referrer" />
            <img className="w-8 h-8 rounded-full border-2 border-white object-cover" src="https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&q=80&w=120" alt="creator" referrerPolicy="no-referrer" />
            <img className="w-8 h-8 rounded-full border-2 border-white object-cover" src="https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?auto=format&fit=crop&q=80&w=120" alt="creator" referrerPolicy="no-referrer" />
            <div className="w-8 h-8 rounded-full border-2 border-white bg-black flex items-center justify-center text-[10px] font-bold text-white font-mono select-none">
              +
            </div>
          </div>
          <p className="text-[11px] text-gray-500 font-semibold font-sans">
            <strong className="text-black font-black">10,000+</strong> creators already using Yourt AI
          </p>
        </div>

        {/* BEFORE & AFTER CINEMATIC REPRESENTATION */}
        <div className="grid grid-cols-1 md:grid-cols-11 items-center gap-6 pt-16 max-w-4xl mx-auto" id="before-after-grid">
          
          {/* Card Left: Before */}
          <div className="md:col-span-5 bg-white border border-gray-150 rounded-3xl p-8 shadow-xs flex flex-col items-center justify-center space-y-6 aspect-video select-none transform hover:scale-99 transition-all">
            <div className="w-16 h-16 rounded-full bg-gray-100 flex items-center justify-center text-gray-400">
              <FileText className="w-7 h-7 stroke-[1.5]" />
            </div>
            <div className="space-y-1 text-center">
              <h4 className="font-display font-extrabold text-[#0D0D0D] text-sm tracking-tight">Scattered Drafting</h4>
              <p className="text-[11px] text-gray-450 leading-relaxed font-sans max-w-[200px]">
                Struggling to write hooks, manually scripting, guessing titles, and managing content schedules offline.
              </p>
            </div>
            <span className="text-[10px] bg-gray-100 text-gray-500 rounded-lg px-2.5 py-1 font-black uppercase tracking-wider font-sans">
              Before
            </span>
          </div>

          {/* Middle Arrow Connector */}
          <div className="md:col-span-1 flex flex-col items-center justify-center gap-2">
            <div className="w-10 h-10 rounded-full bg-[#ff6b00]/10 flex items-center justify-center text-[#ff6b00] transform rotate-90 md:rotate-0">
              <ArrowRight className="w-5 h-5 stroke-[2.5]" />
            </div>
            <span className="text-[9px] text-gray-400 font-mono font-bold tracking-tight uppercase text-center max-w-[80px] hidden md:block">
              AI empowers your workflow
            </span>
          </div>

          {/* Card Right: After */}
          <div className="md:col-span-5 bg-[#FAF9F9] border border-gray-150 rounded-3xl p-6 shadow-sm hover:border-[#ff6b00]/20 transition-all duration-300 flex flex-col justify-between overflow-hidden group select-none transition-all transform hover:scale-101">
            
            {/* YouTube-style Thumbnail Card Mockup */}
            <div className="bg-[#0D0D0D] rounded-2xl overflow-hidden shadow-lg border-0 p-3.5 flex flex-col space-y-2.5">
              {/* Top Banner Text */}
              <div className="text-center font-display uppercase tracking-tight py-1 select-none">
                <div className="text-white text-[11px] md:text-xs font-black tracking-tight">
                  Ranking Funniest <span className="text-[#FFE500]">Thomas</span>
                </div>
                <div className="text-[#FF1111] text-[10px] md:text-[11px] font-black tracking-tighter -mt-0.5">
                  Sanders Storytime Vibes
                </div>
              </div>

              {/* Main Image Stage */}
              <div className="relative aspect-video rounded-xl overflow-hidden bg-neutral-950 border-0">
                <img 
                  className="w-full h-full object-cover" 
                  src="https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?auto=format&fit=crop&q=80&w=400" 
                  alt="viral creator face" 
                  referrerPolicy="no-referrer" 
                />
                
                {/* Level indicators on the left side */}
                <div className="absolute left-2.5 top-1 flex flex-col gap-0.5 font-sans font-black text-[7px] md:text-[8px] text-white tracking-wider drop-shadow-[0_2px_2px_rgba(0,0,0,1)] select-none">
                  <div className="flex items-center">
                    <span className="text-[#39FF14] text-[9.5px]">1.</span>
                  </div>
                  <div className="flex items-center">
                    <span className="text-[#FFE500] text-[9.5px]">2.</span>
                  </div>
                  <div className="flex items-center">
                    <span className="text-[#FF1111] text-[9.5px]">3.</span>
                  </div>
                  <div className="flex items-center">
                    <span>4. LEVEL</span>
                  </div>
                  <div className="flex items-center">
                    <span>5. LEVEL (5)</span>
                  </div>
                  <div className="flex items-center">
                    <span>6. LEVEL (11)</span>
                  </div>
                  <div className="flex items-center">
                    <span>7. LEVEL (3)</span>
                  </div>
                  <div className="flex items-center">
                    <span>8. LEVEL (2)</span>
                  </div>
                  <div className="flex items-center">
                    <span>9. LEVEL (1)</span>
                  </div>
                </div>
              </div>

              {/* Bottom centered 'TIME' indicator */}
              <div className="text-center select-none py-0.5">
                <span className="text-white font-black italic tracking-widest text-[11px] md:text-xs">
                  TIME
                </span>
              </div>
            </div>

            {/* Video Meta Info (Title, Options, View count) */}
            <div className="mt-4 flex items-start justify-between">
              <div className="space-y-1">
                <h4 className="font-display font-black text-[#0D0D0D] text-[13px] md:text-sm tracking-tight leading-snug">
                  Ranking funniest Thomas sanders ...
                </h4>
                <p className="text-[11px] text-[#ff6b00] font-mono font-bold flex items-center gap-1">
                  936K views • 12.8% Est. CTR
                </p>
              </div>
              <div className="text-gray-400 p-1 font-bold text-sm leading-none select-none">
                ⋮
              </div>
            </div>

            {/* Badge for 'After' */}
            <div className="mt-4 pt-3.5 border-t border-gray-150 flex items-center justify-between">
              <div className="flex items-center gap-1.5">
                <span className="w-2 h-2 bg-[#ff6b00] rounded-full animate-ping" />
                <span className="text-[9px] font-black tracking-widest text-gray-500 uppercase font-sans">
                  VIRAL VELOCITY OUTCOME
                </span>
              </div>
              <span className="text-[10px] bg-[#0d0d0d] text-white rounded-lg px-2.5 py-1 font-black uppercase tracking-wider font-sans shadow-3xs">
                After
              </span>
            </div>
          </div>

        </div>

      </section>

      {/* 3. BENTO GRID: THE COMPLETE CREATOR ENGINE */}
      <section className="bg-white border-t border-b border-[#efeded]/70 py-20 px-4 sm:px-6 lg:px-8 select-none" id="features">
        <div className="max-w-[1280px] mx-auto space-y-12">
          
          <div className="text-center space-y-2.5">
            <h2 className="font-display font-black text-3xl sm:text-5xl text-[#0D0D0D] tracking-tight">
              The Complete Creator Engine
            </h2>
            <p className="text-xs sm:text-sm text-gray-500 max-w-xl mx-auto leading-relaxed font-sans">
              Everything you need to go from blank page to viral short, housed in one clean workspace.
            </p>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-3 gap-8 pt-4" id="bento-creator-grid">
            
            {/* Bento Block 1: Idea Generator */}
            <div className="bg-[#fbf9f9] border border-[#efeded] rounded-3xl p-6 flex flex-col justify-between space-y-6 hover:border-[#ff6b00]/30 transition-all duration-200">
              <div className="space-y-4">
                <div className="flex items-center gap-2">
                  <span className="text-[9px] font-bold uppercase tracking-wider text-[#ff6b00] bg-[#ff6b00]/10 px-2 py-0.5 rounded-md font-sans flex items-center gap-1">
                    <Lightbulb className="w-3 h-3" /> Niche Ideas
                  </span>
                </div>
                {/* Visual outline decoration */}
                <div className="bg-white border border-gray-105 rounded-2xl p-4.5 space-y-3">
                  <div className="h-3 w-4/12 bg-gray-200 rounded-md" />
                  <div className="space-y-1.5">
                    <div className="h-2 w-full bg-gray-100 rounded" />
                    <div className="h-2 w-11/12 bg-gray-100 rounded" />
                    <div className="h-2 w-8/12 bg-gray-100 rounded" />
                  </div>
                </div>
              </div>
              
              <div className="space-y-2">
                <h3 className="font-display font-extrabold text-lg text-[#0D0D0D] tracking-tight">
                  Idea Generator
                </h3>
                <p className="text-xs text-gray-550 leading-relaxed font-sans">
                  Input any niche, get 10 proven viral angles backed by high-retention current YouTube search trends.
                </p>
              </div>
            </div>

            {/* Bento Block 2: Hook Generator */}
            <div className="bg-[#fbf9f9] border border-[#efeded] rounded-3xl p-6 flex flex-col justify-between space-y-6 hover:border-[#ff6b00]/30 transition-all duration-200">
              <div className="space-y-4">
                <div className="flex items-center gap-2">
                  <span className="text-[9px] font-bold uppercase tracking-wider text-amber-700 bg-amber-50 px-2 py-0.5 rounded-md font-sans flex items-center gap-1">
                    <Anchor className="w-3 h-3" /> Scroll-Stoppers
                  </span>
                </div>
                {/* Visual outline hook lines */}
                <div className="bg-white border border-gray-105 rounded-2xl p-4.5 space-y-3">
                  <div className="flex justify-between items-center text-[9px] font-bold text-emerald-600 bg-emerald-50 px-2 py-0.5 rounded self-start">
                    <span>First 3 Seconds Safe</span>
                  </div>
                  <div className="space-y-1.5 border-l-2 border-emerald-400 pl-2">
                    <p className="text-[10px] font-semibold text-gray-700 leading-tight">"This single line of code destroyed a..."</p>
                  </div>
                </div>
              </div>

              <div className="space-y-2">
                <h3 className="font-display font-extrabold text-lg text-[#0D0D0D] tracking-tight">
                  Hook Generator
                </h3>
                <p className="text-xs text-gray-550 leading-relaxed font-sans">
                  Generate high-impact opening lines designed to lock in viewer attention within the critical first 3 seconds.
                </p>
              </div>
            </div>

            {/* Bento Block 3: Script Generation */}
            <div className="bg-[#fbf9f9] border border-[#efeded] rounded-3xl p-6 flex flex-col justify-between space-y-6 hover:border-[#ff6b00]/30 transition-all duration-200">
              <div className="space-y-4">
                <div className="flex items-center gap-2">
                  <span className="text-[9px] font-bold uppercase tracking-wider text-black bg-black/5 px-2 py-0.5 rounded-md font-sans flex items-center gap-1">
                    <ScrollText className="w-3 h-3" /> Generated Script
                  </span>
                </div>
                {/* Visual outline script lines */}
                <div className="bg-white border border-gray-105 rounded-2xl p-4.5 space-y-3.5">
                  <div className="flex justify-between items-center">
                    <div className="h-3.5 w-6 bg-orange-100 rounded border border-orange-200/50" />
                    <div className="h-1.5 w-12 bg-gray-100 rounded" />
                  </div>
                  <div className="space-y-2">
                    <div className="flex gap-1.5 items-center">
                      <div className="w-1.5 h-1.5 bg-[#ff6b00] rounded-full" />
                      <div className="h-2 w-10/12 bg-[#efeded] rounded" />
                    </div>
                    <div className="flex gap-1.5 items-center">
                      <span className="w-1.5 h-1.5 bg-gray-300 rounded-full" />
                      <div className="h-2 w-8/12 bg-[#efeded] rounded" />
                    </div>
                  </div>
                </div>
              </div>

              <div className="space-y-2">
                <h3 className="font-display font-extrabold text-lg text-[#0D0D0D] tracking-tight">
                  Script Generation
                </h3>
                <p className="text-xs text-gray-550 leading-relaxed font-sans">
                  Full 60-second scripts paced for high retention, complete with B-roll visual cues and text overlay alerts.
                </p>
              </div>
            </div>

            {/* Bento Block 4: Title Optimization */}
            <div className="bg-[#fbf9f9] border border-[#efeded] rounded-3xl p-6 flex flex-col justify-between space-y-6 hover:border-[#ff6b00]/30 transition-all duration-200">
              <div className="space-y-4">
                <div className="flex items-center justify-between">
                  <span className="text-[9px] font-bold uppercase tracking-wider text-emerald-700 bg-emerald-50 px-2 py-0.5 rounded-md font-sans flex items-center gap-1">
                    <Heading className="w-3 h-3" /> CTR Optimizer
                  </span>
                </div>
                {/* Visual scoring widget representation */}
                <div className="space-y-2">
                  <div className="bg-white border border-gray-105 rounded-xl p-3 flex items-center justify-between">
                    <span className="text-[10px] font-bold text-gray-700 truncate">I tried the viral...</span>
                    <span className="text-[10px] font-black text-emerald-600 bg-emerald-50 px-1.5 py-0.5 rounded">98% Score</span>
                  </div>
                  <div className="bg-white border border-gray-105 rounded-xl p-3 opacity-60 flex items-center justify-between">
                    <span className="text-[10px] font-semibold text-gray-500 truncate">The truth about...</span>
                    <span className="text-[10px] font-bold text-gray-500 bg-gray-100 px-1.5 py-0.5 rounded">72% Score</span>
                  </div>
                </div>
              </div>

              <div className="space-y-2">
                <h3 className="font-display font-extrabold text-lg text-[#0D0D0D] tracking-tight">
                  Title Optimization
                </h3>
                <p className="text-xs text-gray-550 leading-relaxed font-sans">
                  Click-through-rate optimized titles designed to maximize algorithmic push on global feeds.
                </p>
              </div>
            </div>

            {/* Bento Block 5: Hashtag Generator */}
            <div className="bg-[#fbf9f9] border border-[#efeded] rounded-3xl p-6 flex flex-col justify-between space-y-6 hover:border-[#ff6b00]/30 transition-all duration-200">
              <div className="space-y-4">
                <div className="flex items-center gap-2">
                  <span className="text-[9px] font-bold uppercase tracking-wider text-blue-700 bg-blue-50 px-2 py-0.5 rounded-md font-sans flex items-center gap-1">
                    <Hash className="w-3 h-3" /> Organic Reach
                  </span>
                </div>
                {/* Visual hashtags pills */}
                <div className="bg-white border border-gray-105 rounded-2xl p-4 flex flex-wrap gap-2 justify-center">
                  <span className="text-[10px] font-bold bg-[#ff6b00]/5 text-[#ff6b00] border border-[#ff6b00]/10 px-2.5 py-1 rounded-full">#coding</span>
                  <span className="text-[10px] font-bold bg-gray-50 text-gray-600 border border-gray-150 px-2.5 py-1 rounded-full">#techtips</span>
                  <span className="text-[10px] font-bold bg-gray-50 text-gray-600 border border-gray-150 px-2.5 py-1 rounded-full">#creator</span>
                </div>
              </div>

              <div className="space-y-2">
                <h3 className="font-display font-extrabold text-lg text-[#0D0D0D] tracking-tight">
                  Hashtag Generator
                </h3>
                <p className="text-xs text-gray-550 leading-relaxed font-sans">
                  Locate trending, high-volume hashtags tailored to your exact video category to target proper distribution.
                </p>
              </div>
            </div>

            {/* Bento Block 6: Trend Analyzer */}
            <div className="bg-[#fbf9f9] border border-[#efeded] rounded-3xl p-6 flex flex-col justify-between space-y-6 hover:border-[#ff6b00]/30 transition-all duration-200">
              <div className="space-y-4">
                <div className="flex items-center gap-2">
                  <span className="text-[9px] font-bold uppercase tracking-wider text-purple-700 bg-purple-50 px-2 py-0.5 rounded-md font-sans flex items-center gap-1">
                    <ImageIcon className="w-3 h-3" /> Viral Analytics
                  </span>
                </div>
                {/* Visual outline trend analyzer box */}
                <div className="bg-white border border-gray-105 rounded-2xl p-3 h-20 flex items-center justify-between relative overflow-hidden bg-cover bg-center" style={{ backgroundImage: 'linear-gradient(135deg, #fffcf9 0%, #ffe3d1 100%)' }}>
                  <div className="flex flex-col gap-1 select-none">
                    <span className="text-[10px] font-extrabold text-[#ff6b00]">12.8% Est. CTR</span>
                    <span className="text-[8px] font-bold text-emerald-600 bg-emerald-50 px-1 py-0.5 rounded self-start">A-Tier Grade</span>
                  </div>
                  <div className="w-8 h-8 rounded-full bg-[#ff6b00]/10 flex items-center justify-center text-[#ff6b00]">
                    <span className="text-xs font-black">📈</span>
                  </div>
                </div>
              </div>

              <div className="space-y-2">
                <h3 className="font-display font-extrabold text-lg text-[#0D0D0D] tracking-tight">
                  Trend Analyzer &amp; CTR Predictor
                </h3>
                <p className="text-xs text-gray-550 leading-relaxed font-sans">
                  Analyze trending topics, identify competitor gaps, and upload thumbnails or input titles to predict CTR score with high-accuracy Gemini evaluation.
                </p>
              </div>
            </div>

          </div>

        </div>
      </section>

      {/* 4. THREE STEPS ACTION LAYOUT */}
      <section className="py-20 px-4 sm:px-6 lg:px-8 select-none" id="steps">
        <div className="max-w-[1280px] mx-auto space-y-16">
          
          <div className="text-center space-y-3">
            <h2 className="font-display font-black text-3xl sm:text-5xl text-[#0D0D0D] tracking-tight">
              Three Steps to <span className="text-[#ff6b00]">Viral Content</span>
            </h2>
            <p className="text-xs sm:text-sm text-gray-500 max-w-xl mx-auto leading-relaxed font-sans">
              The simplest way to brainstorm, write, and plan professional video concepts
            </p>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-3 gap-10 pt-4" id="steps-cols-layout">
            
            {/* Step 1 */}
            <div className="space-y-5 text-center flex flex-col items-center">
              <div className="relative">
                <div className="w-16 h-16 rounded-3xl bg-gray-100/70 border border-gray-150 flex items-center justify-center text-gray-700">
                  <Lightbulb className="w-6 h-6 stroke-[1.8]" />
                </div>
                <span className="absolute -top-1.5 -right-1.5 bg-[#ff6b00] text-white w-6 h-6 rounded-full flex items-center justify-center text-xs font-black select-none border-2 border-[#fbf9f9]">
                  1
                </span>
              </div>
              <div className="space-y-2 max-w-xs">
                <h3 className="font-display font-extrabold text-[#0D0D0D] text-base sm:text-lg tracking-tight">
                  Input Your Niche or Topic
                </h3>
                <p className="text-xs text-gray-500 leading-relaxed font-sans">
                  Enter your video theme, creator style, or niche category to instantly begin the creative brainstorming process.
                </p>
              </div>
            </div>

            {/* Step 2 */}
            <div className="space-y-5 text-center flex flex-col items-center">
              <div className="relative">
                <div className="w-16 h-16 rounded-3xl bg-gray-100/70 border border-gray-150 flex items-center justify-center text-[#ff6b00]">
                  <Wand2 className="w-6 h-6 stroke-[1.8]" />
                </div>
                <span className="absolute -top-1.5 -right-1.5 bg-[#ff6b00] text-white w-6 h-6 rounded-full flex items-center justify-center text-xs font-black select-none border-2 border-[#fbf9f9]">
                  2
                </span>
              </div>
              <div className="space-y-2 max-w-xs">
                <h3 className="font-display font-extrabold text-[#0D0D0D] text-base sm:text-lg tracking-tight">
                  AI Crafts Creator Assets
                </h3>
                <p className="text-xs text-gray-550 leading-relaxed font-sans">
                  Let our advanced Google Gemini AI write highly engaging titles, scroll-stopping hooks, high-retention video scripts, and tags.
                </p>
              </div>
            </div>

            {/* Step 3 */}
            <div className="space-y-5 text-center flex flex-col items-center">
              <div className="relative">
                <div className="w-16 h-16 rounded-3xl bg-[#0D0D0D] flex items-center justify-center text-white shadow-md">
                  <Calendar className="w-6 h-6 stroke-[1.8] text-[#ff6b00]" />
                </div>
                <span className="absolute -top-1.5 -right-1.5 bg-[#ff6b00] text-white w-6 h-6 rounded-full flex items-center justify-center text-xs font-black select-none border-2 border-[#fbf9f9]">
                  3
                </span>
              </div>
              <div className="space-y-2 max-w-xs">
                <h3 className="font-display font-extrabold text-[#0D0D0D] text-base sm:text-lg tracking-tight">
                  Plan & Schedule
                </h3>
                <p className="text-xs text-gray-550 leading-relaxed font-sans">
                  Organize your creations on the interactive Content Calendar, save your favorite concepts, and deploy them directly to your production queue.
                </p>
              </div>
            </div>

          </div>

        </div>
      </section>

      {/* 5. INTERACTIVE TERMINAL PREVIEW SECTION */}
      <section className="bg-gray-100/40 border-t border-b border-gray-160/60 py-20 px-4 sm:px-6 lg:px-8 select-none" id="preview-section">
        <div className="max-w-[1280px] mx-auto space-y-12">
          
          <div className="text-center space-y-3">
            <h2 className="font-display font-black text-3xl sm:text-5xl text-[#0D0D0D] tracking-tight">
              Ideate. Write. <span className="text-[#ff6b00]">Schedule.</span>
            </h2>
            <p className="text-sm text-gray-500 max-w-xl mx-auto font-sans leading-relaxed">
              Our creator hub keeps your entire workflow synced. Brainstorm clickable hooks, test title variants, generate full scripts, and track your content calendar in one secure workspace.
            </p>
          </div>

          <div className="max-w-4xl mx-auto bg-white border border-gray-200/80 rounded-3xl shadow-xl overflow-hidden" id="interactive-preview">
            
            {/* Mock browser status bar */}
            <div className="bg-[#efeded]/70 px-4 py-3 border-b border-gray-105 flex items-center justify-between">
              <div className="flex gap-1.5 select-none shrink-0">
                <span className="w-2.5 h-2.5 rounded-full bg-red-400 block" />
                <span className="w-2.5 h-2.5 rounded-full bg-yellow-400 block" />
                <span className="w-2.5 h-2.5 rounded-full bg-green-400 block" />
              </div>
              <div className="bg-gray-100 border border-gray-200 px-6 py-0.5 rounded-md text-[10px] text-gray-400 font-mono select-all truncate max-w-xs">
                app.yourtai.com/dashboard
              </div>
              <div className="w-8" />
            </div>

            {/* Simulated Live Panel inside Interactive Card */}
            <div className="p-6 sm:p-8 space-y-6 min-h-[300px]">
              
              {/* Tab Selector inside Card */}
              <div className="flex flex-wrap border-b border-gray-100 pb-2 gap-3 justify-center sm:justify-start font-sans">
                <button
                  onClick={() => setActiveTab("track")}
                  className={`px-4 py-2 rounded-xl text-xs font-bold transition-all cursor-pointer ${
                    activeTab === "track" 
                      ? "bg-[#ff6b00]/10 text-[#ff6b00]" 
                      : "text-gray-500 hover:text-[#0D0D0D]"
                  }`}
                >
                  Workspace Stats
                </button>
                <button
                  onClick={() => setActiveTab("analyze")}
                  className={`px-4 py-2 rounded-xl text-xs font-bold transition-all cursor-pointer ${
                    activeTab === "analyze" 
                      ? "bg-[#ff6b00]/10 text-[#ff6b00]" 
                      : "text-gray-500 hover:text-[#0D0D0D]"
                  }`}
                >
                  Script Analysis
                </button>
                <button
                  onClick={() => setActiveTab("optimize")}
                  className={`px-4 py-2 rounded-xl text-xs font-bold transition-all cursor-pointer ${
                    activeTab === "optimize" 
                      ? "bg-[#ff6b00]/10 text-[#ff6b00]" 
                      : "text-gray-500 hover:text-[#0D0D0D]"
                  }`}
                >
                  Sync Calendar
                </button>
              </div>

              {/* Dynamic displays based on tab selection */}
              <div className="min-h-[180px] animate-fade-in flex flex-col justify-between">
                <AnimatePresence mode="wait">
                  {activeTab === "track" && (
                    <motion.div 
                      key="track"
                      initial={{ opacity: 0, y: 5 }}
                      animate={{ opacity: 1, y: 0 }}
                      exit={{ opacity: 0, y: -5 }}
                      className="grid grid-cols-1 sm:grid-cols-3 gap-4"
                    >
                      <div className="bg-gray-50 border border-gray-100 p-4.5 rounded-2xl flex flex-col justify-between">
                        <span className="text-[10px] uppercase tracking-wider text-gray-400 font-bold font-sans">Generation Speed</span>
                        <p className="font-display font-black text-2xl text-black">&lt; 3.2s</p>
                        <span className="text-[9px] font-bold text-emerald-600 bg-emerald-50 px-1.5 py-0.5 rounded self-start font-sans mt-2">+85% vs legacy models</span>
                      </div>
                      <div className="bg-gray-50 border border-gray-100 p-4.5 rounded-2xl flex flex-col justify-between">
                        <span className="text-[10px] uppercase tracking-wider text-gray-400 font-bold font-sans">Saved Outlines</span>
                        <p className="font-display font-black text-2xl text-black">45 Concepts</p>
                        <span className="text-[9px] font-bold text-emerald-600 bg-emerald-50 px-1.5 py-0.5 rounded self-start font-sans mt-2">Organized in Cloud</span>
                      </div>
                      <div className="bg-gray-50 border border-gray-105 p-4.5 rounded-2xl flex flex-col justify-between">
                        <span className="text-[10px] uppercase tracking-wider text-gray-400 font-bold font-sans">System Status</span>
                        <p className="font-display font-black text-2xl text-[#ff6b00] flex items-center gap-1">
                          <Flame className="w-5 h-5 animate-pulse" /> 100% Active
                        </p>
                        <span className="text-[9px] font-bold text-gray-500 bg-black/5 px-1.5 py-0.5 rounded self-start font-sans mt-2">Gemini Engine Online</span>
                      </div>
                    </motion.div>
                  )}

                  {activeTab === "analyze" && (
                    <motion.div 
                      key="analyze"
                      initial={{ opacity: 0, y: 5 }}
                      animate={{ opacity: 1, y: 0 }}
                      exit={{ opacity: 0, y: -5 }}
                      className="space-y-4"
                    >
                      <div className="bg-gray-50 border border-gray-100 p-4.5 rounded-2xl space-y-3.5">
                        <div className="flex justify-between items-center border-b border-gray-105 pb-2">
                          <span className="text-xs font-bold text-[#0D0D0D] font-display">Semantics Analyzer</span>
                          <span className="text-[9px] font-bold text-[#ff6b00] bg-[#ff6b00]/10 px-2 py-0.5 rounded">Curiosity Hook Triggered</span>
                        </div>
                        <p className="text-xs text-gray-700 italic font-sans leading-relaxed">
                          "This single line of CSS destroyed a $100 Million startup overnight..."
                        </p>
                        <div className="flex gap-4 pt-1 font-mono text-[10px] text-gray-450 border-t border-gray-105">
                          <span>Length: 12 words</span>
                          <span>Contrast rating: 9.8 (High)</span>
                          <span>Estimated retention drift: None</span>
                        </div>
                      </div>
                    </motion.div>
                  )}

                  {activeTab === "optimize" && (
                    <motion.div 
                      key="optimize"
                      initial={{ opacity: 0, y: 5 }}
                      animate={{ opacity: 1, y: 0 }}
                      exit={{ opacity: 0, y: -5 }}
                      className="bg-gray-50 border border-gray-100 p-5 rounded-2xl text-center space-y-3.5"
                    >
                      <div className="w-10 h-10 rounded-full bg-emerald-100 flex items-center justify-center text-emerald-600 mx-auto">
                        <Check className="w-5 h-5 stroke-[2.5]" />
                      </div>
                      <div className="space-y-1">
                        <h4 className="font-display font-extrabold text-sm text-black">Content Queue Synchronized</h4>
                        <p className="text-xs text-gray-450 max-w-md mx-auto leading-relaxed font-sans">
                          Scheduled outlines, scripts, and media resources are securely organized inside your personal Firestore database for immediate access.
                        </p>
                      </div>
                    </motion.div>
                  )}
                </AnimatePresence>
                
                <div className="pt-6 border-t border-gray-100 flex flex-col sm:flex-row sm:items-center sm:justify-between gap-3 text-xs">
                  <span className="text-gray-400 font-mono">Sandbox status represented in real-time</span>
                  <button 
                    onClick={() => onGetStarted("signup")}
                    className="bg-black hover:bg-[#ff6b00] text-white font-bold px-4 py-2 rounded-xl transition-all self-start sm:self-auto flex items-center gap-1.5 cursor-pointer"
                  >
                    Launch Suite
                    <ArrowRight className="w-3.5 h-3.5" />
                  </button>
                </div>
              </div>

            </div>

          </div>

        </div>
      </section>

      {/* 6. PLANS BUILT AROUND OUTPUT: PRICING GRID */}
      <section className="py-20 px-4 sm:px-6 lg:px-8 select-none" id="pricing">
        <div className="max-w-[1280px] mx-auto space-y-16">
          
          <div className="text-center space-y-3">
            <h2 className="font-display font-black text-3xl sm:text-5xl text-[#0D0D0D] tracking-tight">
              Pay-as-you-go Space Credits
            </h2>
            <p className="text-xs sm:text-sm text-gray-500 max-w-xl mx-auto leading-relaxed font-sans">
              No recurring monthly fees. Purchase one-time credit refills that never expire and generate exactly what you need.
            </p>
            <span className="inline-block text-[10px] text-[#ff6b00] font-black uppercase tracking-wider font-mono">
              ★ Standard Refill is the most popular choice for content creators ★
            </span>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-3 gap-8 pt-4 max-w-6xl mx-auto" id="pricing-matrix">
               {/* Card 1: Starter Refuel */}
            <div className="bg-white border border-gray-150 hover:border-gray-250 rounded-3xl p-6 sm:p-8 flex flex-col justify-between space-y-8 transition-all hover:scale-99">
              <div className="space-y-6">
                <div className="space-y-2">
                  <div className="flex items-center gap-1 text-[#ff6b00]">
                    <Zap className="w-4 h-4 stroke-[2]" />
                    <span className="font-display font-black text-sm uppercase tracking-wider">Starter Refuel</span>
                  </div>
                  <p className="text-xs text-gray-500 leading-relaxed font-sans">
                    Ideal for light writers and testing short ideas.
                  </p>
                </div>

                <div className="flex items-baseline gap-1">
                  <span className="font-display font-black text-4xl text-[#0D0D0D]">$4.99</span>
                  <span className="text-xs text-gray-400 font-bold font-sans">one-time</span>
                </div>

                <div className="bg-gray-100/60 border border-gray-105 rounded-2xl p-5 space-y-2 text-center">
                  <span className="font-display font-black text-2xl text-[#FF6B00] block">500</span>
                  <span className="font-sans font-bold text-[10px] uppercase tracking-wider text-gray-500">Space Credits Included</span>
                </div>

                <p className="text-xs text-gray-500 font-sans leading-relaxed text-center">
                  Full, non-expiring access to all creative tools and workspace functions.
                </p>
              </div>

              <button 
                onClick={() => onGetStarted("signup")}
                className="w-full bg-transparent hover:bg-gray-50 text-black border border-gray-250 font-bold py-3.5 rounded-xl text-xs transition-colors cursor-pointer"
              >
                Buy Starter Pack
              </button>
            </div>

            {/* Card 2: Standard Refill (MOST POPULAR) */}
            <div className="bg-white border-2 border-[#ff6b00] rounded-3xl p-6 sm:p-8 flex flex-col justify-between space-y-8 relative overflow-hidden transition-all hover:scale-101 shadow-xl">
              
              {/* Highlight Banner */}
              <div className="absolute top-0 right-0 bg-[#ff6b00] text-white text-[9px] font-black tracking-widest uppercase py-1.5 px-6 leading-none transform rotate-45 translate-x-8 translate-y-4">
                Most Popular
              </div>

              <div className="space-y-6">
                <div className="space-y-2">
                  <div className="flex items-center gap-1.5 text-[#ff6b00]">
                    <Sparkles className="w-4.5 h-4.5 stroke-[2] text-[#ff6b00]" />
                    <span className="font-display font-black text-sm uppercase tracking-wider">Standard Refill</span>
                  </div>
                  <p className="text-xs text-gray-500 leading-relaxed font-sans">
                    Popular choice for active video creators.
                  </p>
                </div>

                <div className="flex items-baseline gap-1">
                  <span className="font-display font-black text-4xl text-[#0D0D0D]">$9.99</span>
                  <span className="text-xs text-gray-400 font-bold font-sans">one-time</span>
                </div>

                <div className="bg-[#fff7f2] border border-[#ff6b00]/15 rounded-2xl p-5 space-y-2 text-center">
                  <span className="font-display font-black text-2xl text-[#ff6b00] block">1,500</span>
                  <span className="font-sans font-bold text-[10px] uppercase tracking-wider text-[#ff6b00]">Space Credits Included</span>
                </div>

                <p className="text-xs text-gray-500 font-sans leading-relaxed text-center">
                  Full access to high-retention templates, smart generators, and premium styles.
                </p>
              </div>

              <button 
                onClick={() => onGetStarted("signup")}
                className="w-full bg-[#ff6b00] hover:bg-[#e05e00] text-white font-bold py-3.5 rounded-xl text-xs transition-colors cursor-pointer shadow-sm hover:shadow-md"
              >
                Buy Standard Pack
              </button>
            </div>

            {/* Card 3: Enterprise Boost */}
            <div className="bg-white border border-gray-150 hover:border-gray-250 rounded-3xl p-6 sm:p-8 flex flex-col justify-between space-y-8 transition-all hover:scale-99">
              <div className="space-y-6">
                <div className="space-y-2">
                  <div className="flex items-center gap-1 text-gray-700">
                    <Layers className="w-4 h-4 stroke-[2]" />
                    <span className="font-display font-black text-sm uppercase tracking-wider">Enterprise Boost</span>
                  </div>
                  <p className="text-xs text-gray-500 leading-relaxed font-sans">
                    For high-volume channels and teams.
                  </p>
                </div>

                <div className="flex items-baseline gap-1">
                  <span className="font-display font-black text-4xl text-[#0D0D0D]">$24.99</span>
                  <span className="text-xs text-gray-400 font-bold font-sans">one-time</span>
                </div>

                <div className="bg-gray-100/60 border border-gray-105 rounded-2xl p-5 space-y-2 text-center">
                  <span className="font-display font-black text-2xl text-gray-800 block">5,000</span>
                  <span className="font-sans font-bold text-[10px] uppercase tracking-wider text-gray-500">Space Credits Included</span>
                </div>

                <p className="text-xs text-gray-500 font-sans leading-relaxed text-center">
                  Maximized allocation to guarantee zero generation locks during critical periods.
                </p>
              </div>

              <button 
                onClick={() => onGetStarted("signup")}
                className="w-full bg-transparent hover:bg-gray-50 text-black border border-gray-250 font-bold py-3.5 rounded-xl text-xs transition-colors cursor-pointer"
              >
                Buy Enterprise Pack
              </button>
            </div>
          </div>

          <p className="text-[10px] text-center text-gray-400 font-sans tracking-wide max-w-lg mx-auto leading-relaxed">
            One-time purchase credits never expire. Use your credits anytime for Commentary, Ranking, or AI clip creation without subscription obligations.
          </p>

        </div>
      </section>

      {/* 7. FREQUENTLY ASKED QUESTIONS SECTION (ACCORDION) */}
      <section className="bg-white border-t border-b border-[#efeded]/70 py-20 px-4 sm:px-6 lg:px-8 select-none" id="faq">
        <div className="max-w-[760px] mx-auto space-y-12">
          
          <div className="text-center space-y-3">
            <span className="text-[10px] font-black uppercase tracking-widest text-gray-400 font-display">Questions</span>
            <h2 className="font-display font-black text-3xl sm:text-5xl text-[#0D0D0D] tracking-tight">
              Frequently Asked Questions
            </h2>
          </div>

          <div className="divide-y divide-gray-150 border-t border-b border-gray-150" id="accordion-container">
            {faqs.map((faq, idx) => {
              const isOpen = openFaq === idx;
              return (
                <div key={idx} className="py-4 font-sans">
                  <button
                    onClick={() => setOpenFaq(isOpen ? null : idx)}
                    className="w-full flex items-center justify-between py-2 text-left font-display font-extrabold text-sm sm:text-base text-[#0d0d0d] hover:text-[#ff6b00] transition-colors cursor-pointer"
                  >
                    <span>{faq.q}</span>
                    {isOpen ? <ChevronUp className="w-5 h-5 text-gray-400" /> : <ChevronDown className="w-5 h-5 text-gray-400" />}
                  </button>
                  
                  {/* Smooth collapse view */}
                  {isOpen && (
                    <div className="pt-2 pb-3 text-xs sm:text-sm text-gray-500 leading-relaxed font-sans max-w-2xl animate-fade-in">
                      {faq.a}
                    </div>
                  )}
                </div>
              );
            })}
          </div>

        </div>
      </section>

      {/* 8. INSTANT GET STARTED FINAL CTA */}
      <section className="bg-[#FAF9F9] py-24 px-4 sm:px-6 lg:px-8 text-center select-none" id="bottom-cta-banner">
        <div className="max-w-[1280px] mx-auto space-y-6">
          <h2 className="font-display font-black text-3xl sm:text-5xl text-[#0d0d0d] tracking-tight leading-tight max-w-xl mx-auto">
            Ready to Create Your First <span className="text-[#ff6b00]">Viral Short?</span>
          </h2>
          <p className="text-xs sm:text-sm text-gray-500 max-w-md mx-auto leading-relaxed font-sans pb-2">
            Join thousands of creators who are already using Yourt AI to grow their channels. Start for free, no credit card required.
          </p>
          <button
            onClick={() => onGetStarted("signup")}
            className="inline-flex items-center justify-center gap-2 bg-[#ff6b00] hover:bg-[#e05e00] hover:scale-101 text-white font-bold text-sm px-8 py-4.5 rounded-2xl transition-all shadow-md cursor-pointer"
            id="bottom-primary-cta"
          >
            Get Started Free
            <ArrowRight className="w-4.5 h-4.5" />
          </button>
        </div>
      </section>

      {/* 9. DETAILED BOTTOM FOOTER WITH NEWSLETTER SECTION */}
      <footer className="border-t border-[#efeded] bg-white pt-16 pb-12 px-4 sm:px-8" id="footer-landing">
        <div className="max-w-[1280px] mx-auto grid grid-cols-1 md:grid-cols-12 gap-8 pb-12 border-b border-gray-150">
          
          {/* Brand Info */}
          <div className="md:col-span-4 space-y-4">
            <div className="flex items-center gap-2.5">
              <YourtLogo size={36} />
              <span className="font-display font-black text-lg text-[#0D0D0D] tracking-tight">Yourt AI</span>
            </div>
            <p className="text-xs text-gray-450 max-w-xs leading-relaxed font-sans">
              Deploy modular generative pipelines on secure cloud configurations to elevate first-3-second organic retention across all algorithms.
            </p>
          </div>

          {/* Legal Nav Links */}
          <div className="md:col-span-2 space-y-3 text-xs">
            <h4 className="font-display font-extrabold text-[#0D0D0D] tracking-wider uppercase text-[10px]">Legal</h4>
            <div className="flex flex-col gap-2 font-medium text-gray-400">
              <a href="#privacy" className="hover:text-[#ff6b00] transition-colors">Privacy Policy</a>
              <a href="#terms" className="hover:text-[#ff6b00] transition-colors">Terms of Service</a>
            </div>
          </div>

          {/* Support Nav Links */}
          <div className="md:col-span-2 space-y-3 text-xs">
            <h4 className="font-display font-extrabold text-[#0D0D0D] tracking-wider uppercase text-[10px]">Support</h4>
            <div className="flex flex-col gap-2 font-medium text-gray-400">
              <a href="#help" onClick={(e) => { e.preventDefault(); onGetStarted("signin"); }} className="hover:text-[#ff6b00] transition-colors">Contact Support</a>
              <a href="#help" onClick={(e) => { e.preventDefault(); onGetStarted("signin"); }} className="hover:text-[#ff6b00] transition-colors">API Docs</a>
            </div>
          </div>

          {/* Stay Updated Newsletter box! */}
          <div className="md:col-span-4 space-y-3 text-xs">
            <h4 className="font-display font-extrabold text-[#0D0D0D] tracking-wider uppercase text-[10px]">Stay Updated</h4>
            
            {newsletterSubscribed ? (
              <div className="p-3 bg-emerald-50 text-emerald-700 border border-emerald-100 rounded-xl leading-relaxed text-[11px] font-sans">
                ✓ Thank you! You've successfully subscribed to our creator insights updates.
              </div>
            ) : (
              <form onSubmit={handleSubscribeNewsletter} className="flex gap-2 max-w-sm">
                <input
                  type="email"
                  required
                  value={email}
                  disabled={newsletterSubscribed}
                  onChange={(e) => setEmail(e.target.value)}
                  placeholder="Enter your email"
                  className="bg-gray-100 focus:bg-white text-xs text-gray-800 border-0 focus:ring-1 focus:ring-[#ff6b00] pl-3.5 pr-2 py-2.5 rounded-xl flex-1 placeholder-gray-405 font-sans"
                />
                <button
                  type="submit"
                  disabled={newsletterSubscribed}
                  className="bg-black hover:bg-[#ff6b00] text-white text-xs font-bold px-4 py-2.5 rounded-xl transition-all cursor-pointer shrink-0"
                >
                  Subscribe
                </button>
              </form>
            )}
            
            <p className="text-[10px] text-gray-400 mt-1 leading-relaxed max-w-[280px]">
              Receive premium optimization guides, retention case studies, and occasional product updates.
            </p>
          </div>

        </div>

        {/* Global Bottom Credits line */}
        <div className="max-w-[1280px] mx-auto flex flex-col sm:flex-row sm:items-center sm:justify-between pt-6 text-[11px] text-gray-400 font-sans gap-2 select-none">
          <p>© 2026 Yourt AI. All rights reserved.</p>
          <div className="flex gap-4 font-semibold text-gray-400">
            <span className="hover:text-[#ff6b00] transition-colors">Designed for Kinetic Minimalism</span>
            <span className="hover:text-[#ff6b00] transition-colors">Powered by Google GenAI</span>
          </div>
        </div>
      </footer>

    </div>
  );
}
